name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Check
      run: make check

    - name: Format
      run: make format

    - name: Test
      run: make test

    - name: Release
      run: cargo build --release

    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Rust Binary Artifact
        path: target/release/week7_test_tool # <-- Ensure the name matches your binary (check toml file)